require 'httparty'
require 'json'
require 'cgi'

require 'infogram/version'
require 'infogram/resources'
require 'infogram/client'
require 'infogram/themes'
require 'infogram/infographics'
require 'infogram/users'
